# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Novemap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Novemap
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire', '~> 4.4.0'
  pod 'PusherSwift', '~> 4.1.0'
end

##
#

